### ISSUE TITLE
generateInputFiles doesn't work

### ISSUE THREAD

**Issue by allgrit** [SimonSchroeder/QMake2Fastbuild#1]
Hi,

I use script generateInputFiles on this file
[addressbook.txt](https://github.com/SimonSchroeder/QMake2Fastbuild/files/5451295/addressbook.txt)
and get nothing in Source and Headres section, only mocs
[files.txt](https://github.com/SimonSchroeder/QMake2Fastbuild/files/5451304/files.txt)
It seems like there is a requirement for spelling of these sections?

**Comment by SimonSchroeder** [comment]
Hi,

Thanks for trying out the scripts. You are right that the scripts need a certain kind of spelling. This is written such that it works with the exact syntax which files generated with Qt Creator provide.

Take a look at this statement from the script, for example:

sed "1,/SOURCES\ +=\ \\/d" MyProject.pro

At the end of the command inside the quotes you see a ‚d‘ which means ‚delete‘. The part between the two slashes ‚/‘ is a search term. This means that starting from the first line up to the search term (including the line with the search term) everything is deleted. The other commands following this will make sure that everything following this line will be used as .Sources in FASTBuild.

Inside the search term certain things have to be escaped by a backslash. The exact line in addressbook.txt would need to look like this: Starts with ‚SOURCES‘ followed by a single space. Then ‚+=‘ (and not just ‚=‘ which isn‘t your problem) followed again with a single space. Finally, the line needs to be terminated with a backslash ‚\‘, meaning that your first source needs to be listed on the next line instead of the same.

I don‘t have quick solution to having the first source on the same line as SOURCES. However, you can write a single star ‚*‘ after each space in the search term to allow for more than one space (i.e. any number of spaces).

The same then applies to HEADERS as well. I hope that these suggestions will help to get everything working.

Good luck!
Simon

**Comment by allgrit** [comment]
Hi,

thank you for detailed answer and your work! Can you add to repo some samples of all three files filled correctly and example of pro file with syntax that you rely on? I'm sure it will be usefull for everybody.

also I have error with moc, have you already seen it?

 '	C:/Qt/Qt5.12.6/5.12.6/msvc2017_64/bin/moc.exe $(DEFINES) --compiler-flavor=msvc .....
[files.bff](https://github.com/SimonSchroeder/QMake2Fastbuild/files/5456945/files2.txt)

FastBuild recognizes $(DEFINES) as variable , that starts with $ but has no ending $.  Error 1028

**Comment by allgrit** [comment]
If I delete $(DEFINES)  from string , I also get error, it looks like "" doesn't work properly with spaces and it read as separate params, 
[error.txt](https://github.com/SimonSchroeder/QMake2Fastbuild/files/5457019/error.txt)
[files.bff](https://github.com/SimonSchroeder/QMake2Fastbuild/files/5457036/files3.txt)

Do you have some ideas how to fix it ?

**Comment by SimonSchroeder** [comment]
I am sorry that I am not able to reply earlier, so that you have to wait one full day every time.

I didn't notice your problems with moc in your first post.

For this, we need to have a look a this line from the script:
`grep "moc.exe $(DEFINES)" Makefile.Release | sed "s/^.*\ ..\\..\\\(src\\.*\)\ -o\ .*moc_.*cpp$/\1/"`

The first part looks for lines containing "moc.exe $(DEFINES)". This means you should not delete "$(DEFINES)" from your generated files. However, the next part of this command needs to be changed for you.

On our system qmake generates backslashes `\` on Windows. It seems that your system generates forward slashes `/` instead. This is one part. The second is, that in our repository the sources are located in a directory called `src`. Your directory structure looks different. You need to change
`sed "s/^.*\ ..\\..\\\(src\\.*\)\ -o\ .*moc_.*cpp$/\1/"`
into
`sed "s/^.*\ \.\.\/\.\.\/\(.*\)\ -o\ .*moc_.*cpp$/\1/"`

To make it slightly more readable, I also suggest to replace the separating character in this sed string:
`sed "s@^.*\ \.\./\.\./\(.*\)\ -o\ .*moc_.*cpp$@\1@"`
This command should take the whole line and separate out only the source file.

1. `^.*` starts a the beginning of the line and consumes as much characters as possible.
1. `\ \.\./\.\./` can be rewritten to ` ../../`. This part we need to discard as well.
1. `\(.*\)` captures as many characters as possible. This will be the file name. In the original script it would capture the directory `src` as well. If you have a directory structure you need to capture everything. Though it might work with the modifications in every conceivable way.
1. Finally, we match ` -o *moc_*cpp` until the end of the line.
1. The `\1` in the statement replaces the whole search string (i.e. from the start of the line `^` until the end of the line `$`) with the first capture, which is the part between `\(` and `\)`.

I hope this helps you to fix up this one line in the script to get it working for your project.

PS: This is the tutorial https://www.grymoire.com/Unix/Sed.html on sed I always go back to to put together sed expressions.

**Comment by allgrit** [comment]
Hi,

I'm grateful for your answer and help. I started from a simplier task - compiled hello world example without qt/mocs/etc... It works.

May you  show example of small project and/or files.bff that works ? It will be easier to understand how to adapt sed commands if I look at structure. Even verbose output gives no clue.

I also got stuck with mocs, it looks like there is no moc_ files generated and I can't understand why.
[log_build.txt](https://github.com/SimonSchroeder/QMake2Fastbuild/files/5464219/log_build.txt)

**Comment by SimonSchroeder** [comment]
I had a quick look at the scripts in a fresh project.

My test project was done with Qt Creator: Just create a new project, select 'Qt Widgets Application'. You can name it 'MyProject' such that you can use the files from this repository without many modifications. Without further changes it gives you a project with a mocable file.

This showed me one problem with `generateInputFiles.bat`. QMake needs a Visual Studio environment to generate any makefiles at all. With your existing script you could call it from a Visual Studio command shell. I also added a call to `vcvarsx64.bat` to the script and check it in to the repository. Furthermore, the script should now work both with forward slashes and backslashes. Also, source files don't need to be in `src` anymore. These are basically the changes I suggested before.

With a few more changes in `fbuild.bff`, `MyProject.bff`, and `VS2019.bff` I was able to compile the unchanged `Qt Widgets Application` using FASTBuild. You should get those new files as well.

**Comment by allgrit** [comment]
Thank you very much! I will try.

**Comment by allgrit** [comment]
Now files.bff filled correctly, but now I got error Failed to spawn process
[log3010.txt](https://github.com/SimonSchroeder/QMake2Fastbuild/files/5465155/log3010.txt)

**Comment by SimonSchroeder** [comment]
This error is hard to debug remotely.

For debugging you should try to run FASTBuild only locally (skip the command line argument `-dist` for now). For more reproducability you can also add `-j1` so that it only runs with a single thread on your local machine.

Here are two things you should check out:
1. Does the dummy.cpp exist in the path my FASTBuild configuration assembles (i.e. C:\Qt\Qt5.12.6\5.12.6\msvc2017_64\mkspecs\features\data\dummy.cpp)?
2. I basically took the parameters for this compilation from QMake's makefile. I suggest that you run QMake on MyProject.pro and have a look at `Makefile.Release`. You should find a line which looks quite similar to the output in your log (containing both dummy.cpp and moc_predefs.h). Compare these to the parameters in MyProject.bff.

If this does not help, try running FASTBuild with options `-showcmds` (which I believe you are already doing) and also `-showcmdoutput`. Especially together with `-j1` this might give more clues as to what is going wrong.

**Comment by allgrit** [comment]
It almost works. I got an error 1> LINK : fatal error LNK1158: cannot run 'rc.exe'
I tried to add path to rc.exe to PATH but It didn't help
[log0211.txt](https://github.com/SimonSchroeder/QMake2Fastbuild/files/5475851/log0211.txt)

I added this to PATH C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64

UPD
I found typo in .Windows10_SDKVersion   and It succ compiled. Thank you very much. I will try to do this on real project.
